language: node_js
before_install:
  - npm i -g grunt-cli
  - sudo apt-get install fluxbox
  - export DISPLAY=:90.0
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_90.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :90 -ac -screen 0 1280x1024x16"
node_js:
  - "0.10"
env:
  - BROWSER=firefox
